### ISSUE TITLE
Attempting to Install on Ubuntu

### ISSUE THREAD

**Issue by LordDarkStar** [jirkapinkas/sitemonitoring-production#10]
Greetings,

Please forgive my ignorance, but I am trying to install your software on my system which is running Ubuntu 16.10 with Gnome 3 for the desktop.  I read your ReadMe file and attempted to install the software by double clicking on the .bat file from the program's directory within my home directory and by opening the program's directory in a terminal session and running the .bat file from Terminal.  I was unsuccessful in both cases.  When I reviewed your video, you were installing the program on a Windows computer.  This leads me to wonder if this software is incompatible with my Linux operating system.

Please advise.

**Comment by jirkapinkas** [comment]
1. delete from startup.bat file all lines before "java -jar ..."
2. run in command line: `chmod +x startup.bat`
3. run in command line: `./startup.bat`
