### ISSUE TITLE
Email test not working for outlook and gmail

### ISSUE THREAD

**Issue by saravananvts** [jirkapinkas/sitemonitoring-production#14]
I have tried test the mail for website monitoring. But, email testing failed for gmail and outlook.

**Outlook:**
I have used the below host and port for email test.
Email server host:  smtp.office365.com / outlook.office365.com
Email server port:  587

It shows the below email test result when test the outlook mail.

org.springframework.mail.MailSendException: Failed messages: com.sun.mail.smtp.SMTPSendFailedException: 530 5.7.57 SMTP;  Client was not authenticated to send anonymous mail during MAIL FROM [MAXPR0101CA0052.INDPRD01.PROD.OUTLOOK.COM]

**Gmail:**
I have tried to test the Gmail with smtp.gmail.com. It throws below error when test the mail.

Port: 465
org.springframework.mail.MailSendException: Mail server connection failed; nested exception is javax.mail.MessagingException: Could not connect to SMTP host: smtp.gmail.com, port: 465, response: -1

Port: 587
org.springframework.mail.MailSendException: Failed messages: com.sun.mail.smtp.SMTPSendFailedException: 530 5.7.0 Must issue a STARTTLS command first. i126sm3226123pfc.101 - gsmtp

**Comment by jirkapinkas** [comment]
Try SendGrid (free). That's what I currently use. Unfortunately different cloud SMTP providers require different "hacks" in configuration (and over time they change it) :-(, so it's impossible to have support for everything :-( When I have some free time I will review gmail integration, because it used to work.

**Comment by jirkapinkas** [comment]
I've stopped working on sitemonitoring and started using Prometheus + AlertManager + Grafana. I'm archiving this project right now.
